### ISSUE TITLE
Non carica i dati

### ISSUE THREAD

**Issue by Sbebo** [Tecnologica-Mente/HUB_Scuola_DRM_Remover#1]
Ciao,
eseguendo un test ricevo il seguente errore:

Obtaining volume info...
undefined:1
Not Found
^

SyntaxError: Unexpected token N in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (file:///D:/Download/HUB_Scuola_DRM_Remover-main/HUB_Scuola_DRM_Remover-main/node_modules/node-fetch/src/body.js:149:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///D:/Download/HUB_Scuola_DRM_Remover-main/HUB_Scuola_DRM_Remover-main/add_update_book_id.js:48:22

Node.js v18.17.1

Press any key to continue...

**Comment by Tecnologica-Mente** [comment]
Salve.

L'errore è dovuto ad un errore sul token. Probabilmente non lo ha copiato correttamente. Il token in genere ha lunghezza 60 caratteri e termina con il carattere = (uguale).

Ho appena testato il funzionamento dello script e funziona perfettamente. Al massimo mi da errore di "Token Session not valid" perchè il token è scaduto. Per ovviare basta ricreare il file di testo.

Riprovi ad eseguire l'operazione di creazione del file di testo con il tasto 2 e poi a scaricare nuovamente il libro con il tasto 3.

Saluti.
