### ISSUE TITLE
Console-Launcher.exe non presente

### ISSUE THREAD

**Issue by dpescatore** [Tecnologica-Mente/HUB_Scuola_DRM_Remover#2]
Ciao, non è presente nella folder scaricata il Console-Launcher.exe che viene richiesto al download dei pacchetti iniziale (tasto 1 del menu principale), non è presente nemmeno all'interno dei file copiati da node.

**Comment by Tecnologica-Mente** [comment]
Ciao. Non si trova in Node.js ma nell'archivio di Python Portable.
