### ISSUE TITLE
Problema PDF

### ISSUE THREAD

**Issue by AlessandroSangiuliano** [Tecnologica-Mente/HUB_Scuola_DRM_Remover#3]
Ciao, seguendo le istruzione scarica, ma purtroppo è un file di un solo Kb, cioè proprio 1Kb, e non può essere aperto. Forse hanno cambiato qualcosa nelle API?

Inoltre su windows anche se ho node js, il menu dal prompt quando schiaccio 2 oppure 3 dice sempre che non trova node.exe, sono quindi costretto a farlo girare manualmente tipo:

node add_update_book_id.js

e successivamente

node download.js

Potresti dargli uno sguardo?

**Comment by Tecnologica-Mente** [comment]
Ciao Alessandro, ti confermo che Hub Scuola DRM Remover è stato bloccato diverso tempo fa.
Per il momento l'unico tool che funziona è pdfgrabber (da cui però hanno rimosso myZanichelli per una richiesta di takedown dalla stessa casa editrice), ma se anche questo non va dovrai attendere una nuova versione dall'autore. Per il momento io non ho tempo di occuparmene.
Saluti

p.s. Il problema di Node.js viene risolto scaricando la versione "Prebuilt binaries" (che a differenza dell'installer è un file .zip) che trovi nella sezione "Download" del sito di Node.js e che va scompattata nella stessa cartella dove si trova il file "Hub_Scuola_DRM_Remover_AIO.cmd". Comunque, se usi pdfgrabber non ti serve.

**Comment by danielsan-dani** [comment]
Ciao, confermo lo stesso problema.
Il pdf aperto con un editor contiene solo `Forbidden`.

**Comment by Tecnologica-Mente** [comment]
Ciao. Usa pdfgrabber

**Comment by danielsan-dani** [comment]
Funziona egregiamente. Grazie!

**Comment by Tecnologica-Mente** [comment]
Figurati. Chiudo la discussione.
